---
- name: Deploy CloudQuill Application to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure old Docker Compose setup is torn down (frees up ports)
      command: docker compose down
      args:
        chdir: /app
      ignore_errors: true

    - name: Build Backend Docker Image
      command: docker build -t cloudquill-backend:latest ./backend
      args:
        chdir: /app

    - name: Build Frontend Docker Image
      # On Windows Docker Desktop, Minikube NodePorts cannot be pinged directly.
      # Instead, we will tunnel the backend later to localhost:30005. So we tell React to hit localhost!
      shell: "docker build --build-arg REACT_APP_API_URL=http://localhost:30005 -t cloudquill-frontend:latest ."
      args:
        chdir: /app

    - name: Load images into Minikube Local Registry (So K8s can find them)
      shell: "docker save cloudquill-backend:latest cloudquill-frontend:latest | docker exec -i minikube docker load"
      ignore_errors: false

    - name: Apply Kubernetes configurations
      command: kubectl apply -f ./k8s
      args:
        chdir: /app

    - name: Force K8s to restart pods and use the new images
      command: kubectl rollout restart deployment frontend backend
      args:
        chdir: /app

    - name: Verify Kubernetes pods are running
      command: kubectl get pods
      register: k8s_status

    - name: Display running K8s pods
      debug:
        var: k8s_status.stdout_lines
